name: travel_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/inter/Inter-Black.ttf
          weight: 900
